export const environment = {
    production: false,
    baseUrl: 'http://localhost:8083/algorithm-visualizer/api/',
    apiUserLogin: 'users/login',
    apiUserRegister: 'users/register',
    apiUserInfo: 'users/info',
    apiProfileInfo: 'users/profile',
    apiGetUserGraphIdsData: 'users/graphs/id',
    apiGetGraphById: 'graphs/',
    apiGetUserMatrixData: 'users/matrices',
    apiGetSupportedAlgorithmsByDataStructure: 'algorithms/',
    apiExecuteGraphAlgorithm: 'algorithms/execute/graph',
    apiCreateDirectedUnweightedGraph: 'graphs/directed/unweighted',
    apiCreateDirectedWeightedGraph: 'graphs/directed/weighted',
    apiCreateUndirectedUnweightedGraph: '/raphs/undirected/unweighted',
    apiCreateUndirectedWeightedGraph: 'graphs/undirected/weighted',
    apiUpdateDirectedUnweightedGraph: 'graphs/directed/unweighted',
    apiUpdateDirectedWeightedGraph: 'graphs/directed/weighted',
    apiUpdateUndirectedUnweightedGraph: 'graphs/undirected/unweighted',
    apiUpdateUndirectedWeightedGraph: 'graphs/undirected/weighted',
    apiExecuteCode: 'code/execute',
    apiCallGemini: 'gemini/explain'
};  