export const environment = {
    production: true,
    baseUrl: 'https://129.148.43.143:8443',
    apiUserLogin: '/users/login',
    apiUserRegister: '/users/register',
    apiUserInfo: '/users/info',
    apiProfileInfo: '/users/profile',
    apiGetUserGraphIdsData: '/users/graphs/id',
    apiGetGraphById: '/graphs/',
    apiGetUserMatrixData: '/users/matrices',
    apiGetSupportedAlgorithmsByDataStructure: '/algorithms/',
    apiExecuteGraphAlgorithm: '/algorithms/execute/graph',
    apiCreateDirectedUnweightedGraph: '/graphs/directed/unweighted',
    apiCreateDirectedWeightedGraph: '/graphs/directed/weighted',
    apiCreateUndirectedUnweightedGraph: '/graphs/undirected/unweighted',
    apiCreateUndirectedWeightedGraph: '/graphs/undirected/weighted',
    apiUpdateDirectedUnweightedGraph: '/graphs/directed/unweighted',
    apiUpdateDirectedWeightedGraph: '/graphs/directed/weighted',
    apiUpdateUndirectedUnweightedGraph: '/graphs/undirected/unweighted',
    apiUpdateUndirectedWeightedGraph: '/graphs/undirected/weighted',
    apiCallGemini: '/gemini/explain'
};