export const environment = {
    production: true,
    baseUrl: 'https://projeto-pw-4syb.onrender.com/',
    apiUserLogin: '/users/login',
    apiUserRegister: '/users/register',
    apiUserInfo: '/users/info',
    apiGetUserGraphIdsData: '/users/graphs/id',
    apiGetGraphById: '/graphs/',
    apiGetUserMatrixData: '/users/matrices',
    apiGetSupportedAlgorithmsByDataStructure: '/algorithms/getStructureSupportedAlgorithms/',
    apiExecuteGraphAlgorithm: '/algorithms/executeGraphAlgorithm',
    apiCreateDirectedUnweightedGraph: '/graphs/createGraph/directed/unweighted',
    apiCreateDirectedWeightedGraph: '/graphs/createGraph/directed/weighted',
    apiCreateUndirectedUnweightedGraph: '/graphs/createGraph/undirected/unweighted',
    apiCreateUndirectedWeightedGraph: '/graphs/createGraph/undirected/weighted',
};