FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libclang-dev \
    g++ \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install clang --break-system-packages

WORKDIR /work